name: Windows Release

on:
    push:
        tags:
          - 'v*.*.*'

    workflow_dispatch:

permissions:
    contents: write

concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3
      - name: 'Set up Python 3.10'
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: 'pip install -r requirements.txt'
      - name: 'Run PyInstaller to build the executable'
        run: |
          pyinstaller --onefile main.py --name susi
      - name: 'Release the build'
        uses: ncipollo/release-action@v1
        with:
          name: 'Release - ${{github.ref_name}}'
          artifacts: 'dist/susi.exe'